INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, SURNAME) VALUES (1, 'Tirlea', 'Stefan');
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, SURNAME) VALUES (2, 'Hanu', 'Bogdan');
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, SURNAME) VALUES (3, 'Sandulache', 'Dumitru');